//subjects source: http://catalog.mit.edu/degree-charts/computer-science-engineering-course-6-3/
const subjects = [
    "Introduction to Computer Science Programming in Python",
    "Mathematics for Computer Science",
    "Oral Communication (CI-M)",
    "Seminar in Undergraduate Advanced Research units, CI-M)",
    "Introduction to EECS via Robotics",
    "Introduction to EECS via Communication Networks",
    "Introduction to EECS via Medical Technology",
    "Introduction to EECS via Interconnected Embedded Systems",
    "Computation Structures",
    "Introduction to Algorithms",
    "Fundamentals of Programming",
    "Elements of Software Construction",
    "Computer Systems Engineering (CI-M)",
    "Artificial Intelligence",
    "Introduction to Machine Learning",
    "Computability and Complexity Theory",
    "Design and Analysis of Algorithms",
    "Fields, Forces and Flows in Biological Systems",
    "Medical Device Design (CI-M)",
    "Biomedical Signal and Image Processing",
    "Biomolecular Feedback Systems",
    "Computer Language Engineering",
    "Computational Biology: Genomes, Networks, Evolution",
    "Introduction to Electric Power Systems",
    "Introductory Analog Electronics Laboratory (CI-M)",
    "Digital Systems Laboratory",
    "Microcomputer Project Laboratory (CI-M)",
    "Microcomputer Project Laboratory - Independent Inquiry",
    "Power Electronics Laboratory (CI-M)",
    "Power Electronics Laboratory - Independent Inquiry",
    "Software Studio",
    "Software Performance Engineering",
    "Constructive Computer Architecture",
    "Networks",
    "Optimization Methods",
    "Solid-State Circuits",
    "Feedback System Design",
    "Introduction to Statistical Data Analysis",
    "Modeling with Machine Learning: from Algorithms to Applications",
    "Statistics, Computation and Applications",
    "Principles of Synthetic Biology",
    "Fundamentals of Photonics",
    "Introduction to Nanoelectronics",
    "Design and Fabrication of Microelectromechanical Systems",
    "Machine Vision",
    "Computational Systems Biology: Deep Learning in the Life Sciences",
    "The Human Intelligence Enterprise",
    "Computational Cognitive Science",
    "Advanced Natural Language Processing",
    "Mobile and Sensor Computing",
    "Engineering Interactive Technologies",
    "Database Systems",
    "Digital and Computational Photography",
    "Multicore Programming",
    "Principles of Autonomy and Decision Making",
    "Dynamic Computer Language Engineering",
    "Advances in Computer Vision",
    "Computer Graphics",
    "Large-scale Symbolic Systems",
    "Theory of Computation",
    "Computer Language Engineering",
    "Computational Biology: Genomes, Networks, Evolution",
    "Digital Systems Laboratory",
    "Microcomputer Project Laboratory - Independent Inquiry (CI-M)",
    "Biological Circuit Engineering Laboratory (CI-M)",
    "Power Electronics Laboratory - Independent Inquiry (CI-M)",
    "Robotics: Science and Systems (CI-M)",
    "Modern Optics Project Laboratory (CI-M)",
    "Strobe Project Laboratory (CI-M)",
    "Software Studio",
    "Software Performance Engineering",
    "Psychoacoustics Project Laboratory (CI-M)",
    "Interactive Music Systems",
    "Parallel Computing and Scientific Machine Learning",
    "Modeling with Machine Learning: from Algorithms to Applications",
    "Statistics, Computation and Applications",
    "Statistics, Computation and Applications",
    "Computational Cognitive Science",
    "Foundations of Information Policy (CI-M)",
    "Advanced Natural Language Processing",
    "Computational Design and Fabrication",
    "Mobile and Sensor Computing",
    "Engineering Interactive Technologies",
    "Principles and Practice of Assistive Technology",
    "Dynamic Computer Language Engineering",
    "Advances in Computer Vision",
    "Advanced Natural Language Processing",
    "Advances in Computer Vision",
    "Machine Learning for Healthcare",
    "Advanced Computational Biology: Genomes, Networks, Evolution",
    "Ethics for Engineers - Independent Inquiry",
    "Large-scale Symbolic Systems",
    "Large-scale Symbolic Systems",
    "Seminar in Undergraduate Advanced Research"
];
//names source: https://www.ssa.gov/oact/babynames/
const students = ['Liam', 'Olivia', 'Noah', 'Emma', 'Oliver', 'Ava', 'Elijah', 'Charlotte', 'William', 'Sophia', 'James', 'Amelia', 'Benjamin', 'Isabella', 'Lucas', 'Mia', 'Henry', 'Evelyn', 'Alexander', 'Harper'];